apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-api
spec:
  selector:
    matchLabels:
      app: article-api
  replicas: 2
  template:
    metadata:
      labels:
        app: article-api
    spec:
      containers:
      - name: article-api
        image: 
        ports:
        - containerPort: 
